/**
 * useAddSnippet - Custom hook for creating new code snippets
 * 
 * This hook manages the complete form state and logic for adding new snippets
 * to the application. It provides real-time language auto-detection, form
 * validation, and keyboard shortcuts for improved developer experience.
 * 
 * Features:
 * - Auto-detection of programming languages from code content
 * - Manual language selection with fallback to auto-detection
 * - Keyboard shortcuts (Ctrl/Cmd+S to save)
 * - Form state management and validation
 * - Async snippet creation with error handling
 * - Automatic navigation after successful creation
 * 
 * The hook integrates with the language detection system to automatically
 * identify the programming language based on code patterns and syntax.
 * 
 * @param addSnippet - Async function to create snippet in storage
 * @param navigate - Navigation function for routing after creation
 */

import type { Snippet } from "../types/snippet";
import { useState, useEffect, useMemo, useCallback } from "react";
import { detectLanguageWithHeuristics, type AutoDetectResult } from "../utils/languageDetection";

export const useAddSnippet = (
  addSnippet: (snippet: Snippet) => Promise<void>,
  navigate: (path: string) => void,
) => {
  // Form state for snippet creation
  const [snippetTitle, setSnippetTitle] = useState("");
  const [snippetLanguage, setSnippetLanguage] = useState("auto");
  const [snippetCode, setSnippetCode] = useState("");

  /**
   * Auto-detect programming language from code content
   * Uses memoization to avoid expensive re-calculations on every render
   * Only runs detection when code content actually changes
   */
  const autoDetectResult = useMemo((): AutoDetectResult | null => {
    if (snippetCode.trim()) {
      return detectLanguageWithHeuristics(snippetCode);
    }
    return null;
  }, [snippetCode]);

  /**
   * Handle changes to snippet title input
   * Simple controlled input handler for the title field
   */
  const handleSnippetTitleChange = (
    event: React.ChangeEvent<HTMLInputElement>,
  ) => {
    setSnippetTitle(event.target.value);
  };

  /**
   * Handle changes to language selection
   * Supports both manual selection and auto-detection mode
   */
  const handleSnippetLanguageChange = (value: string) => {
    setSnippetLanguage(value);
  };

  /**
   * Handle changes to code content
   * Updates code state which triggers language auto-detection
   */
  const handleSnippetCodeChange = (value: string) => {
    setSnippetCode(value);
  };

  /**
   * Handle snippet creation and submission
   * 
   * Creates a new snippet with the form data, handling language detection
   * and navigation. Uses async/await for proper error handling.
   * 
   * Language selection logic:
   * 1. If user selected a specific language, use that
   * 2. If "auto" is selected and detection succeeded, use detected language
   * 3. Otherwise, keep "auto" as the language value
   */
  const handleAddSnippet = useCallback(async (event: React.MouseEvent<HTMLButtonElement>) => {
    event.preventDefault();
    
    // Determine final language based on user selection and auto-detection
    let finalLanguage = snippetLanguage;
    if (snippetLanguage === 'auto' && autoDetectResult) {
      finalLanguage = autoDetectResult.language;
    }
    
    // Create new snippet object (ID will be auto-generated by provider)
    const newSnippet: Snippet = {
      id: 0, // Placeholder ID - will be replaced by provider
      title: snippetTitle,
      language: finalLanguage,
      code: snippetCode,
    };
    
    try {
      await addSnippet(newSnippet);
      navigate("/snippets"); // Navigate to snippets page on success
    } catch (error) {
      console.error("Failed to add snippet:", error);
      // TODO: Show user-friendly error message
    }
  }, [snippetTitle, snippetLanguage, snippetCode, autoDetectResult, addSnippet, navigate]);

  /**
   * Keyboard shortcuts for improved UX
   * 
   * Supports Ctrl+S (Windows/Linux) and Cmd+S (Mac) to save snippet
   * Only triggers if both title and code are provided
   */
  const handleKeyDown = useCallback((event: KeyboardEvent) => {
    if ((event.ctrlKey || event.metaKey) && event.key === 's') {
      event.preventDefault();
      if (snippetTitle.trim() && snippetCode.trim()) {
        handleAddSnippet({ preventDefault: () => {} } as React.MouseEvent<HTMLButtonElement>);
      }
    }
  }, [snippetTitle, snippetCode, handleAddSnippet]);

  /**
   * Set up global keyboard event listeners
   * Automatically cleans up listeners when component unmounts
   */
  useEffect(() => {
    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  }, [handleKeyDown]);

  /**
   * Return hook interface for component usage
   * Provides all form state, handlers, and auto-detection results
   */
  return {
    // Form state
    snippetTitle,
    snippetLanguage, 
    snippetCode,
    
    // Auto-detection results for UI feedback
    autoDetectResult,
    
    // Event handlers for form controls
    handleSnippetTitleChange,
    handleSnippetLanguageChange,
    handleSnippetCodeChange,
    handleAddSnippet,
  };
};
